spring.application.name=ierbar_web_app

spring.datasource.url=jdbc:postgresql://ep-muddy-cell-ask39rs4.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_jm8wPIy7dKQG

spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG

server.port=8080


jwt.secret="Cheie_Ultra_Secreta_Misterioasa_Pentru_Ierbarel_App_2026"
